### ISSUE TITLE
raw parameter does not work

### ISSUE THREAD

**Issue by saibotma** [excitement-engineer/ktor-graphql#21]
When using the raw parameter in the browser like `localhost:8080/graphql?raw` then not the raw schema but `{"errors":[{"message":"Must provide query string."}]}` gets returned.

Using version 2.0.0.

**Comment by excitement-engineer** [comment]
Isn't this the expected behaviour? When you pass the raw parameter you are executing graphQL directly instead of presenting the playground. This parameter does not return the raw schema
