### ISSUE TITLE
Problem passing a Context after updating to v2.0.0

### ISSUE THREAD

**Issue by BoD** [excitement-engineer/ktor-graphql#22]
Hi!

I'm trying to update to v2.0.0, and can't figure out how to pass a Context. Following the example in the Readme, here's what's happening (sorry about the screenshot, but it's the most efficient way of showing both the code and the resulting error):

<img width="832" alt="Screen Shot 2020-12-13 at 16 18 38" src="https://user-images.githubusercontent.com/372852/102016092-5dcf8280-3d5f-11eb-8151-d4b495a251b0.png">

It looks like it's finding the wrong "execute" method?

Also it doesn't help that the [sample](https://github.com/excitement-engineer/ktor-graphql-example) still uses v1.0.0 😀

Thanks a lot for your help.

**Comment by JulianBissekkou** [comment]
@excitement-engineer I also need this feature. Can you quickly update us on the status here?

**Comment by JulianBissekkou** [comment]
@BoD 
I removed the lib and I am now using a little more code than before, but at least it's working now and I have full control. 

Here is the source if you are interested:
https://github.com/camuthig/ktor-social-graphql/pull/2/files

**Comment by excitement-engineer** [comment]
Hey, thanks for the issue. I did update the sample but I forgot to push it to master. See [branch v2](https://github.com/excitement-engineer/ktor-graphql-example/blob/v2/src/main/kotlin/server.kt). In this branch the code worked for me.

Could you maybe create a PR replicating this issue? It seems like you are calling the execute function on the pipeline and not graphQL if I see correctly

**Comment by excitement-engineer** [comment]
I found the solution. You guys are calling the `graphQL` route function instead of the graphQL executor, that is why it is giving errors.

You need to define `graphql` variable using GraphQL-Java and then call it:

```
val graphql = GraphQL.newGraphQL(graphQLSchema).build()
```

**Comment by BoD** [comment]
Thanks a lot, that worked!
