### ISSUE TITLE
UTF-8 does not work

### ISSUE THREAD

**Issue by dsaborg-waya** [excitement-engineer/ktor-graphql#23]
Because we use receiveText and no content charset is passed, Ktor defaults to using ISO-8859-1 as the charset which mangles the UTF-8 encoded JSON. See: https://github.com/ktorio/ktor/issues/384

**Comment by JulianBissekkou** [comment]
@dsaborg-waya  Is there a workaround? The maintainer of this project isn't checking the issues very often

**Comment by excitement-engineer** [comment]
I just published v2.0.1 that fixes the issue. Thanks a lot for your issue and helping improve the library, really appreciate it!
