### ISSUE TITLE
Not compatible with Ktor 2.0

### ISSUE THREAD

**Issue by antweb** [excitement-engineer/ktor-graphql#28]
Hi!

This library can no longer be used with the latest Ktor versions. Specifically, the following code

```kotlin
fun Route.graphql(schema: GraphQLSchema) {
    val graphql = GraphQL.newGraphQL(schema).build()

    authenticate("token") {
        graphQL("/graphql", schema) { request ->
            ...

            Config(
                executeRequest = {
                    graphql.execute(executionInput)
                }
            )
        }
    }
}
```
fails to build with Ktor 2.0.2:
```
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun Route.graphQL(path: String, schema: GraphQLSchema, setup: (PipelineContext<Unit, ApplicationCall>.(GraphQLRequest) -> Config)? = ...): Route defined in ktor.graphql
```
Not a huge surprise, since Ktor changed a ton of imports for the major release.

I saw the branch `update-deps-may-2022` already bumps the dependencies and updates imports in 26d3f57a66d10c32cce41203222c9d035d14e7aa. This is indeed enough to fix the build for my case.

Are you planning to release this anytime soon? I'm happy to help out with the changes should anything still be missing.

**Comment by excitement-engineer** [comment]
I added ktor 2.0 support and also updated the graphql-java dependency. Sorry for the wait.
