### ISSUE TITLE
Test failures when running with graphql-java v13.0

### ISSUE THREAD

**Issue by plm** [excitement-engineer/ktor-graphql#7]
Reviewing the test failures for 4848840 on the v0.13 branch, the root cause appears to be [changes to `ktor.graphql.RequestHandler`](https://github.com/excitement-engineer/ktor-graphql/commit/484884023719bb5e889e599a4f84e17dcde1e9d9#diff-fde25f5a23fb8749c3a577a44512cbdcR244) which reproduce a static method [removed from `graphql.InvalidSyntaxError`](https://github.com/graphql-java/graphql-java/compare/v9.0...v13.0#diff-1d56c0c932428dcb7cc35314f4f05087). The `InvalidSyntaxError` message formatting also changed between v9.0 and v13.0.

The `ktor.graphql.ErrorHandlingTest` test case failure is caused by a different JSON serialization of the error message. The syntax error test seems like it depends heavily on implementation details of graphql-java and how exception messages are formatted.

Even when matching the raw exception type, `graphql.parser.InvalidSyntaxException`, and then calling [`toInvalidSyntaxError()`](https://github.com/graphql-java/graphql-java/blob/v13.0/src/main/java/graphql/parser/InvalidSyntaxException.java#L43) will depend on non-public implementation details marked as `@graphql.Internal` to the parser and potentially at risk of breaking changes.

The lowest-effort fix is seems to be updating the test case to match the revised error message content.

**Comment by plm** [comment]
I noticed that the current conversion of an `Exception` to `InvalidSyntaxError` results in inconsistencies in the instance created as part of the failed test case. The error's message indicates the syntax error is at column "1" but the associated `graphql.language.SourceLocation` indicates column "0".

Using `InvalidSyntaxException#toInvalidSyntaxError()` addresses this inconsistency and results in less code at the cost of depending upon an internal (and v13.0-specific) API.

**Comment by excitement-engineer** [comment]
I just released v1.0.0 that has support for v13.0.0 of graphql-java. Hopefully this fixes the issue:)
